spring:
  application:
    name: eureka
eureka:
  server:
    enable-self-preservation: false # 是否开启自我保护机制
    renewal-percent-threshold: 0.85 # 阈值
    eviction-interval-timer-in-ms: 1000 # 剔除间隔的时间(一般设置的小些,以达快速下线)
    use-read-only-response-cache: false # 关闭readOnlyCache
    response-cache-update-interval-ms: 10000 # 默认30s从readWriteCacheMap中同步数据到readOnlyCacheMap
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-7900:7900/eureka/ #,http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/
---
spring:
  profiles: 7900
server:
  port: 7900
# \u5982\u679C\u4F60\u914D\u7F6E\u4E86 hostname\u540C\u65F6\u53C8\u60F3\u5728url\u4E2D\u4F7F\u7528 eureka-7900 \u90A3\u4E48\u4F60\u9700\u8981\u5728host\u4E2D\u914D\u7F6E 127.0.0.1 eureka-7900
eureka:
  instance:
    hostname: eureka-7900
---
spring:
  profiles: 7901
server:
  port: 7901
eureka:
  instance:
    hostname: eureka-7901

---
spring:
  profiles: 7902
server:
  port: 7902
eureka:
  instance:
    hostname: eureka-7902